### ISSUE TITLE
Create a form for playing music

### ISSUE THREAD

**Issue by kentaro-ueda** [kentaro-ueda/Hello-GitHub#2]
# TODO
- [x] Implement a play function
- [ ] Add UI resources to the project
- [ ] Arrange the UI components
- [ ] Check the behavior

# Screen preview
![btn01_sq](https://user-images.githubusercontent.com/93248383/139358743-73e82fe4-743b-44c3-a1a0-899364b2b959.png)

# References
- [MediaPlayer](https://developer.apple.com/reference/mediaplayer)

**Comment by kentaro-ueda** [comment]
# Results
![image](https://cloud.githubusercontent.com/assets/23502707/2471154/be8cc87a-0c0e-11e7-8955-38f5561842eb.png)
